Integrate releasr logic into workflow

diff --git a/.github/workflows/pkg_published_trigger_build_release.yaml b/.github/workflows/pkg_published_trigger_build_release.yaml
--- a/.github/workflows/pkg_published_trigger_build_release.yaml
+++ b/.github/workflows/pkg_published_trigger_build_release.yaml
@@ -22,7 +22,7 @@ on:
           - 'releases-us.mondoo.io'
           - 'releases-com-test'
       reindex-path:
-        description: 'Path to Reindex (Optional)'
+        description: 'Path to Reindex (e.g. 8.99.99)'
         required: false
         type: string
       reindex-full:
@@ -80,15 +80,68 @@ jobs:
       with:
         app-id: ${{ secrets.MONDOO_MERGEBOT_APP_ID }}
         private-key: ${{ secrets.MONDOO_MERGEBOT_APP_PRIVATE_KEY }}
-    - name: Reindex folder on releaser.mondoo.com
+        owner: mondoohq
+        repositories: |
+          installer
+          releasr
+    - name: Reindex folder on releases.mondoo.com
       uses: peter-evans/repository-dispatch@v3
-      env:
-        VERSION: ${{ needs.parse-inputs.outputs.version }}
       with:
         token: ${{ steps.generate-token.outputs.token }}
         repository: "mondoohq/releasr"
         event-type: reindex
         client-payload: '{
-          "reindex-path": "mondoo/${{ env.VERSION }}",
-          "bucket": "releases-us.mondoo.io"
+          "reindex-path": "mondoo/${{ inputs.reindex-path }}",
+          "bucket": "${{ needs.parse-inputs.outputs.bucket }}"
           }'
+
+    - name: Converge Inputs
+      id: inputs
+      run: |
+        echo "bucket=${{ needs.parse-inputs.outputs.bucket }}" >> $GITHUB_OUTPUT
+        echo "reindex-path=${{ inputs.reindex-path }}" >> $GITHUB_OUTPUT
+    - name: 'Authenticate to Google Cloud'
+      uses: 'google-github-actions/auth@v2'
+      with:
+        credentials_json: '${{secrets.GCP_CREDENTIALS}}'
+    - name: 'Set up Cloud SDK'
+      uses: 'google-github-actions/setup-gcloud@v2'
+    - name: Get GCP TOKEN
+      id: auth
+      run:
+        echo "id_token=$(gcloud auth print-identity-token)" >> "$GITHUB_OUTPUT"
+    - name: Get latest Releasr Binary
+      uses: robinraju/release-downloader@v1.11
+      with:
+        repository: mondoohq/releasr
+        latest: true
+        fileName: releasr
+        out-file-path: .
+        token: ${{ steps.generate-token.outputs.token }}
+    - name: Make releasr executable
+      run: |
+        chmod +x releasr
+    - name: 'Remove Artifacts.json & Index.html from path (Optional)'
+      if: ${{ needs.parse-inputs.outputs.skip-publish != 'true' }}
+      run: |
+        if [ -n "${{ inputs.reindex-path }}" ]; then
+          echo "Removing artifacts.json & index.html from path ${{ inputs.reindex-path }}"
+          # If the files don't exist this will fail, but that's ok
+          gsutil rm gs://${{ needs.parse-inputs.outputs.bucket }}/${{ inputs.reindex-path }}/artifacts.json || true
+          gsutil rm gs://${{ needs.parse-inputs.outputs.bucket }}/${{ inputs.reindex-path }}/index.html || true
+        fi
+    - name: Regenerate Release Indexes
+      if: ${{ needs.parse-inputs.outputs.skip-publish != 'true' }}
+      env:
+        TOKEN: ${{ steps.auth.outputs.id_token }}
+        BUCKETNAME: ${{ steps.inputs.outputs.bucket }}
+        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      run: |
+        if [ "${{ github.event.inputs.reindex-full }}" = "true" ]; then
+          ./releasr idx gs://${{ steps.inputs.outputs.bucket }} --force-recompute
+        else
+          ./releasr idx gs://${{ steps.inputs.outputs.bucket }}
+        fi
+    - name: Invalidate Google Load Balancer caches
+      run: |
+        gcloud compute url-maps invalidate-cdn-cache releases-mondoo-io --path "/${{ inputs.reindex-path }}" --async
